[build]
  command = "npm ci && npm run build:force"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"
  # Configure secrets scanning to omit EmailJS public credentials
  SECRETS_SCAN_OMIT_KEYS = "VITE_EMAILJS_PUBLIC_KEY,VITE_EMAILJS_SERVICE_ID,VITE_EMAILJS_TEMPLATE_ID"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
